### ISSUE TITLE
Confirmation for subs

### ISSUE THREAD

**Issue by calebmer** [calebmer/accelerate#5]
One more feature request 😊:

Can we require a confirmation whenever a user is about to do a sub operation? This can protect people from accidentally deleting a lot of data on production databases.

This could take the form of:
1. If you are performing a sub operation ask for a yes or no to continue in the cli.
2. Add an auto confirm flag for automation.

**Comment by svmnotn** [comment]
this would happen on anything that ends up performing a sub, right?
So the commands affected would be all but add, up, ls, and create

**Comment by calebmer** [comment]
Yep.

**Comment by svmnotn** [comment]
Will do next

**Comment by svmnotn** [comment]
What should the auto ignore flag look like?

**Comment by svmnotn** [comment]
Ok I went with --yes and -y, so it is now implemented in #2 in commit 2b18d12

**Comment by svmnotn** [comment]
Closed with 2b18d12
